
Milestone 3
=================================================
Nama  : Azward Nurfauzan

Batch : CODA-018-RMT

Google Slide : https://docs.google.com/presentation/d/1domm1pOKR65_yONkger93pplwBakHo_nk6Ap8jEp2MA/edit?slide=id.gf11272de0f_0_51#slide=id.gf11272de0f_0_51

Program ini dibuat untuk melakukan proses Pre-Automasi dan penerapan 7 great expectations

## 1. Libraries

In [16]:
import pandas as pd
from great_expectations.data_context import FileDataContext

## 2. Read Dataset (.csv)

Link dataset : https://www.kaggle.com/datasets/muqaddasejaz/customer-support-ticket-dataset

In [2]:
df = pd.read_csv('data/customer_support_tickets.csv')

## 3. Exploratory Data Analysis

### 3.1. Display the top 5 rows

In [3]:
df.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

### 3.2. Display dataset information

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ticket ID                     8469 non-null   int64
 1   Customer Name                 8469 non-null   str
 2   Customer Email                8469 non-null   str
 3   Customer Age                  8469 non-null   int64
 4   Customer Gender               8469 non-null   str
 5   Product Purchased             8469 non-null   str
 6   Date of Purchase              8469 non-null   str
 7   Ticket Type                   8469 non-null   str
 8   Ticket Subject                8469 non-null   str
 9   Ticket Description            8469 non-null   str
 10  Ticket Status                 8469 non-null   str
 11  Resolution                    2769 non-null   str
 12  Ticket Priority               8469 non-null   str
 13  Ticket Channel                8469 non-null   str
 14  First Response Time           5650 non-null   str
 15  Time to Resolution            2769 non-null   str
 16  Customer Satisfaction Rating  2769 non-null   float64
dtypes: float64(1), int64(2), str(14)
memory usage: 1.1 MB

### 3.3. Display Missing Values for Each Column

In [5]:
df.isnull().sum()

Ticket ID                          0
Customer Name                      0
Customer Email                     0
Customer Age                       0
Customer Gender                    0
Product Purchased                  0
Date of Purchase                   0
Ticket Type                        0
Ticket Subject                     0
Ticket Description                 0
Ticket Status                      0
Resolution                      5700
Ticket Priority                    0
Ticket Channel                     0
First Response Time             2819
Time to Resolution              5700
Customer Satisfaction Rating    5700
dtype: int64

### 3.4. Display the Number of Duplicate Data

In [6]:
df.duplicated().sum()

0

### 3.5. Display descriptive statistics

In [7]:
df.describe()

         Ticket ID  Customer Age  Customer Satisfaction Rating
count  8469.000000   8469.000000                   2769.000000
mean   4235.000000     44.026804                      2.991333
std    2444.934048     15.296112                      1.407016
min       1.000000     18.000000                      1.000000
25%    2118.000000     31.000000                      2.000000
50%    4235.000000     44.000000                      3.000000
75%    6352.000000     57.000000                      4.000000
max    8469.000000     70.000000                      5.000000

## 4. Data Adjustment

### 4.1. Analyzing Missing Value Correlation with Ticket Status

In [8]:
df.groupby('Ticket Status')[[
    'Resolution',
    'First Response Time',
    'Time to Resolution',
    'Customer Satisfaction Rating'
]].apply(lambda x: x.isnull().sum())

,Resolution,First Response Time,Time to Resolution,Customer Satisfaction Rating
Ticket Status,,,,
Closed,0,0,0,0
Open,2819,2819,2819,2819
Pending Customer Response,2881,0,2881,2881

Missing values ​​are assumed to be ongoing processes (not yet closed), so the data is left as is.

### 4.2. Handling Data Types

In [9]:
# Date of Purchase menjadi tipe datetime
df["Date of Purchase"] = pd.to_datetime(df["Date of Purchase"],errors="coerce")

# First Response Time menjadi tipe datetime
df["First Response Time"] = pd.to_datetime(df["First Response Time"],errors="coerce")

# Time to Resolution menjadi tipe datetime
df["Time to Resolution"] = pd.to_datetime(df["Time to Resolution"],errors="coerce")

### 4.3. Check Data Types

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ticket ID                     8469 non-null   int64
 1   Customer Name                 8469 non-null   str
 2   Customer Email                8469 non-null   str
 3   Customer Age                  8469 non-null   int64
 4   Customer Gender               8469 non-null   str
 5   Product Purchased             8469 non-null   str
 6   Date of Purchase              8469 non-null   datetime64[us]
 7   Ticket Type                   8469 non-null   str
 8   Ticket Subject                8469 non-null   str
 9   Ticket Description            8469 non-null   str
 10  Ticket Status                 8469 non-null   str
 11  Resolution                    2769 non-null   str
 12  Ticket Priority               8469 non-null   str
 13  Ticket Channel                8469 non-null   str
 14  First Response Time           5650 non-null   datetime64[us]
 15  Time to Resolution            2769 non-null   datetime64[us]
 16  Customer Satisfaction Rating  2769 non-null   float64
dtypes: datetime64[us](3), float64(1), int64(2), str(11)
memory usage: 1.1 MB

## 5. Data Validation

### 5.1. Data Context

In [22]:
# Create a data context
context = FileDataContext.create(project_root_dir='./')

### 5.2. Connect to A Datasource

In [23]:
# Datasource
datasource_name = 'csv-customer-support'
datasource = context.sources.add_pandas(datasource_name)

# Data Asset
asset_name = 'customer-support-ticket'
path_to_data = './data/customer_support_tickets.csv'
asset = datasource.add_csv_asset(asset_name,filepath_or_buffer=path_to_data)

# Build Batch Request
batch_request = asset.build_batch_request()

### 5.3. Create an Expectation Suite

In [24]:
# Create an expectation suite
expectation_suite_name = 'expectation-customer-support'
context.add_or_update_expectation_suite(expectation_suite_name=expectation_suite_name)

# Create a validator using above expectation suite
validator = context.get_validator(
    batch_request=batch_request,
    expectation_suite_name=expectation_suite_name
)

# check the validator
validator.head()

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

### 5.4. Great Expectation

#### 5.4.1. Expectation 1: Ticket ID Must Be Unique

In [25]:
validator.expect_column_values_to_be_unique(
    'Ticket ID'
)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 8469,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

#### 5.4.2. Expectation 2: Customer Age Must Be Between 0 and 100

In [26]:
validator.expect_column_values_to_be_between(
    'Customer Age',
    min_value=0,
    max_value=100
)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 8469,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

#### 5.4.3. Expectation 3: Ticket Status Must Contain Valid Categories

In [27]:
validator.expect_column_values_to_be_in_set(
    'Ticket Status',
    ['Open', 'Closed', 'Pending Customer Response']
)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 8469,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

#### 5.4.4. Expectation 4: Customer Age Must Be an Integer

In [28]:
validator.expect_column_values_to_be_in_type_list(
    'Customer Age',
    ['int64', 'int32']
)

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "observed_value": "int64"
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

#### 5.4.5. Expectation 5: Ticket ID Must Not Be Null

In [29]:
validator.expect_column_values_to_not_be_null(
    'Ticket ID'
)

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 8469,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": []
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

#### 5.4.6. Expectation 6: Average Customer Age Must Be Within an Expected Range

In [ ]:
validator.expect_column_mean_to_be_between(
    "Customer Age",
    min_value=20,
    max_value=60
)

Calculating Metrics:   0%|          | 0/4 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "observed_value": 44.02680363679301
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

#### 5.4.7. Expectation 7: Date of Purchase Must Follow the YYYY-MM-DD Format

In [31]:
validator.expect_column_values_to_match_strftime_format(
    'Date of Purchase',
    '%Y-%m-%d'
)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 8469,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

### 5.5. Save Into Expectation Suite

In [32]:
validator.save_expectation_suite(discard_failed_expectations=False)

### 5.6. Checkpoint

In [33]:
# Create a checkpoint
checkpoint = context.add_or_update_checkpoint(
    name="checkpoint-customer-support",
    validator=validator
)

# Run a checkpoint
checkpoint_result = checkpoint.run()

Calculating Metrics:   0%|          | 0/35 [00:00<?, ?it/s]

### 5.7. Data Docs

In [34]:
# Build data docs
context.build_data_docs()

{'local_site': 'file://d:\\Belajar\\Hactiv8\\milestone\\milestone_3\\p2-coda018-rmt-m3-AzwardFauzan\\gx\\uncommitted/data_docs/local_site/index.html'}